### ISSUE TITLE
Support multiple calendars in one import

### ISSUE THREAD

**Issue by C4ptainCrunch** [C4ptainCrunch/ics.py#10]
See ics/icalendar.py l47

**Comment by derek1lght** [comment]
Is there a workaround for this?  I need to be able to work with multiple calendars at the same time.

**Comment by aureooms** [comment]
You can create a new calendar and assign it a set of events. Create the set by merging the sets of the calendars you want to merge.

**Comment by aureooms** [comment]
See [here](https://github.com/aureooms/dotfiles/blob/master/.bin/calendar._all#L175) for an example.
