### ISSUE TITLE
All day events have a time set (and therefore render incorrectly)

### ISSUE THREAD

**Issue by gomox** [C4ptainCrunch/ics.py#100]
It is my understanding that in order for an event to be all-day, the date has to be specified without a time. For my code that explicitely calls `make_all_day()`, here's sample output:

```
DTSTART:20170816T000000Z 
SUMMARY:test 
LOCATION:BCN-ORY 
UID:8678fbff-d5c6-481d-90a1-1265f29b9cf8@8678.org 
END:VEVENT
```

**Comment by gomox** [comment]
Apparently this is fixed in master but was never released.

**Comment by C4ptainCrunch** [comment]
Release coming soon :)
