### ISSUE TITLE
Update Arrow support to 0.11

### ISSUE THREAD

**Issue by jekku0966** [C4ptainCrunch/ics.py#101]
Currently used Arrow version does not support `.shift()` which is easer to get tomorrows date.

Any workaround available?

**Comment by C4ptainCrunch** [comment]
The Arrow API changed quite a lot, the update won't be trivial unfortunately :/
Bumping the arrow version is in my todo list but not at the very top (recurring events first). I might also choose to drop arrow and use the stdlib + some custom parsing functions, we'll see...

**Comment by C4ptainCrunch** [comment]
Duplicate of #77
