### ISSUE TITLE
Retrieving recurring events for a given day

### ISSUE THREAD

**Issue by martinarroyo** [C4ptainCrunch/ics.py#102]
I am having some difficulties when trying to retrieve a list of events for a given day. In particular, I can't find a way to retrieve recurring events. Here is what I have tried so far:

```python
c = Calendar(urllib_request.urlopen(url).read().decode('utf-8')) # load calendar
events = list(filter(lambda e: e.begin.date() == date_filter, c.events))
```

In this particular calendar, there are 4 events for today. One of them is recurring, and it is not retrieved. If I check the entire list of events, I see that there is one entry for each recurring event, namely the first one in the series.

I also tried using the `Timeline` object:

```python
c.timeline.on(arrow.utcnow())
```

With the same result. I know that there are some known issues with regard to recurring events (#14, #53, #75), so I would just like to know if there is any way to use this package for this particular case.

Thanks in advance!

**Comment by prysme01** [comment]
Hi, I am running into the same problem, I can't get recurring event, I've tried with event.today and event.now

**Comment by C4ptainCrunch** [comment]
Right now, recurring events are not supported, ics.py will only see the first occurrence, sorry :/ 
Nevertheless it's on the roadmap to support them :) (when i'll have time to deal with the API)
