### ISSUE TITLE
import from file example, import from string seems broken

### ISSUE THREAD

**Issue by fsiler** [C4ptainCrunch/ics.py#106]
The url offered on the documentation page is dead, so that's not a helpful example.  I tried with both a toy file and a real file with several hundred events, and get a similar answer.

    In [9]: with open("test.ics", "rb") as f:
       ...:     a = f.read()
       ...:     
    
    In [10]: a
    Out[10]: b'BEGIN:VCALENDAR\r\nPRODID:-//Google Inc//Google Calendar 70.9054//EN\r\nVERSION:2.0\r\nCALSCALE:GREGORIAN\r\nMETHOD:PUBLISH\r\nX-WR-CALNAME:Legal Work\r\nX-WR-TIMEZONE:America/Chicago\r\nX-WR-CALDESC:\r\nBEGIN:VTIMEZONE\r\nTZID:America/Chicago\r\nX-LIC-LOCATION:America/Chicago\r\nBEGIN:DAYLIGHT\r\nTZOFFSETFROM:-0600\r\nTZOFFSETTO:-0500\r\nTZNAME:CDT\r\nDTSTART:19700308T020000\r\nRRULE:FREQ=YEARLY;BYMONTH=3;BYDAY=2SU\r\nEND:DAYLIGHT\r\nBEGIN:STANDARD\r\nTZOFFSETFROM:-0500\r\nTZOFFSETTO:-0600\r\nTZNAME:CST\r\nDTSTART:19701101T020000\r\nRRULE:FREQ=YEARLY;BYMONTH=11;BYDAY=1SU\r\nEND:STANDARD\r\nEND:VTIMEZONE\r\nBEGIN:VEVENT\r\nDTSTART:20131009T202000Z\r\nDTEND:20131009T204000Z\r\nDTSTAMP:20170313T032658Z\r\nUID:005C7E14-8D7A-45AE-9836-22F92AE33ECA\r\nCREATED:20131009T233310Z\r\nDESCRIPTION:\r\nLAST-MODIFIED:20160815T215614Z\r\nLOCATION:\r\nSEQUENCE:6\r\nSTATUS:CONFIRMED\r\nSUMMARY:Holl:: continuance\r\nTRANSP:OPAQUE\r\nX-APPLE-TRAVEL-ADVISORY-BEHAVIOR:AUTOMATIC\r\nEND:VEVENT\r\nBEGIN:VEVENT\r\nDTSTART:20150826T134500Z\r\nDTEND:20150826T142100Z\r\nDTSTAMP:20170313T032658Z\r\nUID:0073507A-67FD-4264-A71F-9143C88B4F36\r\nCREATED:20150826T142454Z\r\nDESCRIPTION:\r\nLAST-MODIFIED:20160815T215614Z\r\nLOCATION:\r\nSEQUENCE:8\r\nSTATUS:CONFIRMED\r\nSUMMARY:Plummer:: call with Chance\\, amend letter\\, call with Couchman\r\nTRANSP:OPAQUE\r\nX-APPLE-TRAVEL-ADVISORY-BEHAVIOR:AUTOMATIC\r\nEND:VEVENT\r\nBEGIN:VEVENT\r\nDTSTART:20151130T192000Z\r\nDTEND:20151130T193700Z\r\nDTSTAMP:20170313T032658Z\r\nUID:00A58CA8-55CE-42BA-8333-C0D4DA82BA3D\r\nCREATED:20151130T194740Z\r\nDESCRIPTION:\r\nLAST-MODIFIED:20160815T215614Z\r\nLOCATION:\r\nSEQUENCE:5\r\nSTATUS:CONFIRMED\r\nSUMMARY:Voelker:: brig conference\\, check with Div5 re appt orders\r\nTRANSP:OPAQUE\r\nX-APPLE-TRAVEL-ADVISORY-BEHAVIOR:AUTOMATIC\r\nEND:VEVENT\r\nEND:VCALENDAR\r\n'
    
    In [11]: c = Calendar(a)
    ---------------------------------------------------------------------------
    AttributeError                            Traceback (most recent call last)
    <ipython-input-11-f7461943b300> in <module>()
    ----> 1 c = Calendar(a)
    
    ~/Library/Python/3.6/lib/python/site-packages/ics/icalendar.py in __init__(self, imports, events, creator)
         60                 container = string_to_container(imports)
         61             elif isinstance(imports, collections.Iterable):
    ---> 62                 container = lines_to_container(imports)
         63             else:
         64                 raise TypeError("Expecting a sequence or a string")
    
    ~/Library/Python/3.6/lib/python/site-packages/ics/parse.py in lines_to_container(lines)
        160 
        161 def lines_to_container(lines):
    --> 162     return parse(tokenize_line(unfold_lines(lines)))
        163 
        164 
    
    ~/Library/Python/3.6/lib/python/site-packages/ics/parse.py in parse(tokenized_lines, block_name)
        151 def parse(tokenized_lines, block_name=None):
        152     res = []
    --> 153     for line in tokenized_lines:
        154         if line.name == 'BEGIN':
        155             res.append(Container.parse(line.value, tokenized_lines))
    
    ~/Library/Python/3.6/lib/python/site-packages/ics/parse.py in tokenize_line(unfolded_lines)
        145 
        146 def tokenize_line(unfolded_lines):
    --> 147     for line in unfolded_lines:
        148         yield ContentLine.parse(line)
        149 
    
    ~/Library/Python/3.6/lib/python/site-packages/ics/parse.py in unfold_lines(physical_lines)
        130     current_line = ''
        131     for line in physical_lines:
    --> 132         if len(line.strip()) == 0:
        133             continue
        134         elif not current_line:
    
    AttributeError: 'int' object has no attribute 'strip'

**Comment by fsiler** [comment]
Aha!  This is fixed when I remove the `rb` flags to `open()`.  However, it would still be helpful to get a useful error message.

**Comment by C4ptainCrunch** [comment]
I merged (very late) your PR, thanks :)
