### ISSUE TITLE
How can I set an Organizer?

### ISSUE THREAD

**Issue by j10sanders** [C4ptainCrunch/ics.py#120]
When I make calendar events, the event in google cal says "Who:	Unknown Organizer*"

How do I set an organizer?  I don't see anything in the docs, or the event api.  I've tried:

   `e = Event()  
      e.begin = time  
      e.duration = {"minutes": 30}  
      e.organizer = 'testemail@gmail.com'`

**Comment by Oscarato** [comment]
Someone know about this?

**Comment by danieltellez** [comment]
It looks like this is a new feature, because ORGANIZER tag is not yet supported, AFAIK.

**Comment by C4ptainCrunch** [comment]
Indeed, the `ORGANIZER` property is not yet supported :/
But if you need it, you should be able to implement it quite easily :) (PR are welcome)

**Comment by C4ptainCrunch** [comment]
PR #138 might be of interest if you try to implement this as both properties are of type `CAL-ADDRESS`

**Comment by C4ptainCrunch** [comment]
Should be there in 0.5 thanks to #167 and #112
