### ISSUE TITLE
Format of all day events

### ISSUE THREAD

**Issue by pchtsp** [C4ptainCrunch/ics.py#121]
First of all thanks for this awesome library! It's really easy to use.

When exporting all day events, Google Calendar expects the following format:

    DTSTART;VALUE=DATE:20171202

Instead, the information exported is in this format:

    DTSTART:20171202T000000Z

I have seen that Google Calendar interprets correctly the following:

    DTSTART;VALUE=DATE:20171202T000000Z

So the only difference is to add the `;VALUE=DATE` just before the timestamp when writing the start.

This has been mentioned in #92 but I thought it was worth a separate issue.

Thanks!

**Comment by C4ptainCrunch** [comment]
```python
e = Event(begin="2015/12/21", end="2016/01/01")
e.make_all_day()
print(e)
```
now outputs
```
BEGIN:VEVENT
DTSTAMP:20181028T220722Z
DTSTART;VALUE=DATE:20151221
DTEND;VALUE=DATE:20160101
TRANSP:OPAQUE
UID:e3f1ee25-72c7-4310-b1fd-8935d2eee099@e3f1.org
END:VEVENT
```
so the issue is closed :)
