### ISSUE TITLE
New Release

### ISSUE THREAD

**Issue by pedromorgan** [C4ptainCrunch/ics.py#125]
Is there a release soon ? am particular interested in the TODO. tia

**Comment by C4ptainCrunch** [comment]
My timing is always a bit unsure but i'm planning a release this week :)
(It will also be the last release to support Python 2 and 3.3)

**Comment by C4ptainCrunch** [comment]
It went faster than expected. ics.py 0.4 is out !

**Comment by pedromorgan** [comment]
thanks @C4ptainCrunch :1st_place_medal: -)
