### ISSUE TITLE
ACTION:NONE Invalid alarm action

### ISSUE THREAD

**Issue by aureooms** [C4ptainCrunch/ics.py#127]
I got a calendar (google) with the following type of alarms. Does not look like it is in the RFC.

    BEGIN:VALARM
    ACTION:NONE
    ...
    END:VALARM

Current code throws an Exception with message `Invalid alarm action`.

**Comment by MHohenberg** [comment]
Just to put my hat into the ring: I have this issue as well. 

This is not a 'feature request', IMHO, but a showstopper-level bug.

**Comment by aureooms** [comment]
We could have options to choose the RFC-compliance strictness level. The checking part could be a separate plugin.

**Comment by balzer82** [comment]
As a workaround I simply solved it by manipulating the ics string like this:

```python
ics = requests.get(url).text
ics = ics.replace('BEGIN:VALARM\r\nACTION:NONE','BEGIN:VALARM\r\nACTION:DISPLAY\r\nDESCRIPTION:')
c = Calendar(ics)
```

**Comment by n2o** [comment]
I am having the same issue when reading a Nextcloud Calendar and a `ACTION:EMAIL` description in it.
