### ISSUE TITLE
Cancel an event

### ISSUE THREAD

**Issue by jjconti** [C4ptainCrunch/ics.py#128]
How can I cancel an event?

**Comment by corey-rb** [comment]
Is there any update for this?

**Comment by C4ptainCrunch** [comment]
Hello @jjconti. I guess you are talking about the `STATUS` property of an event (https://tools.ietf.org/html/rfc5545#section-3.8.1.11) ? Right now we don't have support for it, but it should be quite easy for you to implement if you need it :)

**Comment by C4ptainCrunch** [comment]
Closed by #112, will be released in 0.5
