### ISSUE TITLE
Adding alarms to Event Objects

### ISSUE THREAD

**Issue by SebastienBah** [C4ptainCrunch/ics.py#130]
Unless I'm mistaken, it is not possible to pass an Alarm to Event seeing as how the Event.alarms is a set and Alarm Objects are unhashable. 
```python
class Event(Component):
    def __init__(self, ...):
        ...
        self.alarms = set()
        ...
        if alarms is not None:
            self.alarms.update(set(alarms))
```

Furthermore, in **ics.py/tests/alarm**, the `test_alarm_without_repeat_extraction` function treats the alarms of Event as a list (in the sense of how it accesses the first alarm):
```python
    def test_alarm_without_repeat_extraction(self):
        c = Calendar(cal21)
        a = c.events[0].alarms[0]
        ...
```

**Comment by HUSSTECH** [comment]
The Alarm base class does not implement quite enough to be hashable. I think it is just missing a `__hash__` method, `__eq__` is already there. I have worked around it without needed to fork by subclassing and defining the hash method myself.

```
from ics import DisplayAlarm
from datetime import timedelta


class DisplayAlarm2(DisplayAlarm):
    def __hash__(self):
        return hash(repr(self))


a = DisplayAlarm2(description="hello", trigger=timedelta(minutes=15))

s = set([a])
```

**Comment by Hawkzed** [comment]
Can confirm that Husstech's changes fixed my issue of not being able to add alarms to events.

**Comment by vladox** [comment]
I almost went crazy looking why this wasn't working, is this package still maintained? 
It's really buggy and not well maintained

**Comment by C4ptainCrunch** [comment]
@vladox I'm trying to maintain the project in my free time but it's not easy, sorry about that.
