### ISSUE TITLE
list of Event or set of Event ?

### ISSUE THREAD

**Issue by Maienfelder** [C4ptainCrunch/ics.py#147]
The documentation for v0.4 says: 

**the API contains:**
events (**list** of Event) – :class:`ics.event.Event`s to be added to the calendar

**in an Example we find:**
`c.events.append(e)` 
what results in the error message: "AttributeError: 'set' object has no attribute 'append"

Hence Calendar.events seems to be a set of Event not a list of Event.

changing the example into
`c.events.add(e)` 
does what is expected.

I suppose, the documentation is not updated.

**Comment by aureooms** [comment]
This is in a pull request that has not been merged yet (https://github.com/C4ptainCrunch/ics.py/pull/141).

**Comment by C4ptainCrunch** [comment]
#141 has been merged. Thanks @aureooms for the fix and @Maienfelder for the report :)

**Comment by mohammadg** [comment]
Using ics (0.4) with python 3.6 and I still had to use `c.events.add(e)` instead of `c.events.append(e)`.

**Comment by jacobjorvang** [comment]
Documentation is still wrong.
