### ISSUE TITLE
Update to collections.abc

### ISSUE THREAD

**Issue by ROldford** [C4ptainCrunch/ics.py#149]
ABCs in collections will be removed in Python 3.8, according to this DeprecationWarning:

`/parse.py:137: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working`

parse.py should be updated to use collections.abc.

**Comment by C4ptainCrunch** [comment]
You are right, i'll add this to my backlog of tasks, thanks for filing the issue :)

**Comment by C4ptainCrunch** [comment]
3.8 is almost out, i should fix this
