### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by jkaberg** [C4ptainCrunch/ics.py#153]
Been a while, 0.5 far off? 🙏

**Comment by C4ptainCrunch** [comment]
Hi \o/

I need at least to fix the bug in #92 (and maybe merge #112) then i can release :)
But i can't give you an ETA, i work on ics.py only when i have some time ;)

**Comment by C4ptainCrunch** [comment]
0.5 was published a few minutes ago, have fun !

(Note that #92 and other all-day events bugs are not yet fixed)
