### ISSUE TITLE
Attribute Error

### ISSUE THREAD

**Issue by xyzajacf** [C4ptainCrunch/ics.py#158]
Why I am seeing this error:
Traceback (most recent call last):
```
  File "filename.py", line 45, in <module>
    c = Calendar(); c.append(Event(name="My cool event"))
AttributeError: 'Calendar' object has no attribute 'append'
```
It's caused by the example in documentation
```
c = Calendar(); c.append(Event(name="My cool event"))
open('my.ics', 'w').writelines(c)
```
Am I missing something?

**Comment by reverie** [comment]
@xyzajacf looks like it should now be `c.events.add(...`

**Comment by C4ptainCrunch** [comment]
Indeed, the doc is incorrect (same as #176) i'll fix that soon. Sorry about that :'(
