### ISSUE TITLE
Email action for alarms

### ISSUE THREAD

**Issue by aceisace** [C4ptainCrunch/ics.py#165]
@C4ptainCrunch 
Hi, sorry for opening yet another issue when the last one has not even been resolved yet. What I wanted to ask is if you could implement the Email action in your code, for the following snippet, when you get the time to:
```
   @classmethod
    def get_type_from_action(cls, action_type):
        # TODO: Implement EMAIL action
        if action_type == 'DISPLAY':
            return DisplayAlarm
        elif action_type == 'AUDIO':
            return AudioAlarm

        raise ValueError('Invalid alarm action')
```

If it is going to take a lot of time implementing the new feature, what would be the temporary solution to this error? Thanks in advance.
```
AlarmFactory.get_type_from_action(action_type.value) File "/home/pi/.local/lib/python3.5/site-packages/ics/alarm.py", line 36, in get_type_from_action raise ValueError('Invalid alarm action') ValueError: Invalid alarm action
```

**Comment by texnofobix** [comment]
I am using this library for read-only purposes and found:

```python
    @classmethod
    def get_type_from_action(cls, action_type):
        # TODO: Implement EMAIL action
        if action_type == 'DISPLAY':
            return DisplayAlarm
        elif action_type == 'AUDIO':
            return AudioAlarm
        elif action_type == 'EMAIL':
            return None 
```

**Comment by aceisace** [comment]
@texnofobix
Hi, thanks for your reply. Using your snippet is also an option, but I‘d rather not change the library files. Instead, I‘m looking for a way to ‚bypass‘ these errors within a script. 

What‘s more, some iCalendars do not have any action at all for some events. In that case, a different error (invalid alarm action) will be raised.

**Comment by C4ptainCrunch** [comment]
I thought this was a feature request but in fact it's a bug. This lib should be able to parse any valid calendar (and maybe ignore the parts of the spec it does not know, but not crash on it).
I guess that we should return a default type of alarm if we do not recognize the type.

**Comment by aceisace** [comment]
@C4ptainCrunch 
Yes, that would be a good idea since it will at least allow a calid iCalendar to be parsed. But I think an option whether or not to use the alarms at all would be even better, for example:

```
use_alarms = False (may be a parameter in the calendar function)
```
then, do the following (remove all alarms from all events)
```
decode = str(urlopen(icalendars).read().decode())
beginAlarmIndex = 0
while beginAlarmIndex >= 0:
    beginAlarmIndex = decode.find('BEGIN:VALARM')
if beginAlarmIndex >= 0:
    endAlarmIndex = decode.find('END:VALARM')
    decode = decode[:beginAlarmIndex] + decode[endAlarmIndex+12:]
ical = Calendar(decode)
```

**Comment by C4ptainCrunch** [comment]
This would lead to data loss, i'm not a fan of the idea. Usually, we try to ignore things we can not parse but not remove it :)

**Comment by aceisace** [comment]
@C4ptainCrunch 
As long as the parsing of the events works without any problem, it's fine :)

**Comment by kopf** [comment]
Hey, I would love to use ics.py for its friendly API, but the lack of this feature is preventing me - any way I can help out on PR #183 ?

**Comment by C4ptainCrunch** [comment]
Hi @kopf ! 
Of course, help is always welcome :)

#183 already contains a refactoring but not yet the EmailAlarm. If you could write something that looks like this https://github.com/C4ptainCrunch/ics.py/blob/467166d6cf6ce883ccaaeadac3eb6a8463e90d65/ics/alarm/audio.py i could finish the rest of the PR

**Comment by kopf** [comment]
Hey @C4ptainCrunch - thanks for the quick reply. Super. I'll have a look now.

**Comment by kopf** [comment]
Hi @C4ptainCrunch - a couple of things:

while VALARMS of type `AUDIO` can contain a maximum of 1 attachment, VALARMS of type `EMAIL` can contain multiple attachments. This muddies the semantics of the `self.attach` and `self.attach_params` attributes which imply only one attachment. What should be done in this case? Turn both into lists which can then be `zip`ped together? Or rename the attributes? 

And unfortunately I just realised that what was blocking me wasn't the lack of the `EMAIL` type .. :) What's blocking me is the lack of support for VALARMS of type `NONE`. This type isn't mentioned in the RFC that I can see, and I don't know what's generating them - icalendar on OS X, or the Outlook / Exchange server that it's syncing with. In any event, what would you like to do in a case like this? And would you mind if I focused on solving this problem, at least first of all, as it's the real blocker in my case? :)

**Comment by C4ptainCrunch** [comment]
@kopf You can take a look at #183 if you want. Following your comment i removed `.attach` and `attach_params` all together and replaced it by more meaningful attributes for each type. I also added the NoneAlarm and also a (untested at the moment) CustomAlarm so if somebody make an `ACTION:YOLO` it would not crash.
