### ISSUE TITLE
update doc: append --> add

### ISSUE THREAD

**Issue by xaratustrah** [C4ptainCrunch/ics.py#176]
hi. maybe a doc update is needed here:

https://github.com/C4ptainCrunch/ics.py/blob/bd918ec7453a7cf73a906cdcc78bd88eb4bab71b/ics/icalendar.py#L91

from:
`c.append`
to:
`c.events.add`

thanks!

**Comment by C4ptainCrunch** [comment]
Fixed, thanks @xaratustrah !
