### ISSUE TITLE
Support for events lasting multiple days ?

### ISSUE THREAD

**Issue by ozone89** [C4ptainCrunch/ics.py#184]
I was using a calendar with such events, and tried to get one of those, but got empty result

**Comment by C4ptainCrunch** [comment]
Hi @ozone89 
Could you provide a minimal example showcasing your problem ? as far as i know, ics.py should be able to handle your case.

**Comment by ozone89** [comment]
Sorry if the code is not up to standards :)

Here's an example of such event
```
BEGIN:VEVENT
DTSTAMP:20180713T105935Z
SUMMARY:OFF
UID:1531785600000OFF
DTSTART;VALUE=DATE:20180717
DTEND;VALUE=DATE:20180720
LOCATION:[REDACTED]
DESCRIPTION:
END:VEVENT
```
if I use the timeline.today function for a day with any other event, it works, but for the above event it doesn't.

Also, it's to be noted that regular events have DTSTART and DTEND defined as (example)
```
DTSTART:20180720T030000Z
DTEND:20180720T081500Z
```

```
BEGIN:VEVENT
DTSTAMP:20190426T223511Z
SUMMARY:[REDACTED]
UID:1532044800000[REDACTED]
DTSTART:20180720T030000Z
DTEND:20180720T081500Z
LOCATION:[REDACTED]
DESCRIPTION:
END:VEVENT
```

**Comment by C4ptainCrunch** [comment]
I'm still not sure to understand what you want to do, but maybe you could have a look at all-day events :) See [`Event.make_all_day()`](https://icspy.readthedocs.io/en/stable/api.html#ics.event.Event.make_all_day) and [`Event.all_day`](https://icspy.readthedocs.io/en/stable/api.html#ics.event.Event.all_day).
Please note that there are some known bugs in the implementation of all-day events (see [@N-Coder's summary in #155](https://github.com/C4ptainCrunch/ics.py/issues/155#issuecomment-502993642))

**Comment by ozone89** [comment]
I'm trying to get the events happening on a given day, whether they last on a defined time frame, a whole day, or multiple days, as long they're happening on that day (final intention is to fetch events from two days ago to two days from now) :)

To do it, I was trying to use [`Timeline.today()`](https://icspy.readthedocs.io/en/stable/api.html#ics.timeline.Timeline.today), but it doesn't seem to return events like the first type I've pasted.

It does seem to work for the time-frame defined ones, tho.

**Comment by N-Coder** [comment]
This could be related to whether the `strict` parameter is set or not and whether the exact instant when the event ends is still considered included or not. I can't 100% reproduce what you are talking about, so could you post a [minimal working example](https://stackoverflow.com/help/minimal-reproducible-example) to show what happens and what the result that you would be expecting is? Then I can turn this into a unit test and ensure that future version show the intended behaviour. :wink:

**Comment by ozone89** [comment]
Closing, managed to parse events in another way, and don't remember the (most likely wrong :P) code I was using, sorry for wasting your time
