### ISSUE TITLE
Option override PRODID at import time ?

### ISSUE THREAD

**Issue by jasonehines** [C4ptainCrunch/ics.py#195]
It seems that Apple's icloud public calendar doesn't have a PRODID. Here's the header from mine 
```
BEGIN:VCALENDAR
VERSION:2.0
X-WR-CALNAME:Jason Hines
X-APPLE-CALENDAR-COLOR:#996633
BEGIN:VEVENT
```
Is there someway to override the PRODID when importing?

**Comment by C4ptainCrunch** [comment]
Hi @jasonehines 
At the moment there is no way to override the PRODID when importing as the rfc requires the PRODID.
As a workaround, you could just add a fake PRODID as the second line of your calendar?
