### ISSUE TITLE
Import error

### ISSUE THREAD

**Issue by alex27riva** [C4ptainCrunch/ics.py#196]
Hi, I installed this module with `pip install ics` , but I'm getting this error:
`ImportError: cannot import name 'Calendar' from 'ics' (c:\Users\Alessandro\Desktop\ics.py)`
I'm on a Windows 10 machine.

**Comment by C4ptainCrunch** [comment]
Hi @alex27riva 

Could you give me more information about your system ? What python version are you using ? (try `python --version`).
Could you give me the output of `pip freeze` ?
Could what version of pip are you using ? Try `pip --version`

This looks more like a problem with your installation than with ics.py :)

**Comment by alex27riva** [comment]
Hi, I'm using Python 3.7.3.
Output of `pip freeze`:
`aiohttp==3.5.4
arrow==0.11.0
astroid==2.2.5
async-timeout==3.0.1
attrs==19.1.0
autopep8==1.4.4
backcall==0.1.0
bleach==3.1.0
certifi==2019.6.16
chardet==3.0.4
Click==7.0
colorama==0.4.1
console-menu==0.5.1
cycler==0.10.0
decorator==4.4.0
defusedxml==0.6.0
dnspython==1.15.0
dnspython3==1.15.0
entrypoints==0.3
icalendar==4.0.3
ics==0.5
idna==2.8
ipykernel==5.1.2
ipython==7.7.0
ipython-genutils==0.2.0
ipywidgets==7.5.1
isort==4.3.17
jedi==0.15.1
Jinja2==2.10.1
jsonschema==3.0.2
jupyter==1.0.0
jupyter-client==5.3.1
jupyter-console==6.0.0
jupyter-core==4.5.0
kiwisolver==1.1.0
lazy-object-proxy==1.3.1
MarkupSafe==1.1.1
matplotlib==3.0.3
mccabe==0.6.1
mcstatus==2.2
mistune==0.8.4
multidict==4.5.2
nbconvert==5.6.0
nbformat==4.4.0
notebook==6.0.1
numpy==1.16.3
pandocfilters==1.4.2
parso==0.5.1
pickleshare==0.7.5
prometheus-client==0.7.1
prompt-toolkit==2.0.9
pycodestyle==2.5.0
Pygments==2.4.2
pylint==2.3.1
pyparsing==2.4.0
pyrsistent==0.15.4
pyTelegramBotAPI==3.6.6
python-dateutil==2.8.0
python-nmap==0.6.1
pytz==2019.2
pywinpty==0.5.5
pyzmq==18.1.0
qtconsole==4.5.4
requests==2.7.0
scipy==1.2.1
Send2Trash==1.5.0
six==1.12.0
telebot==0.0.3
telepot==12.7
terminado==0.8.2
testpath==0.4.2
tornado==6.0.3
traitlets==4.3.2
typed-ast==1.3.4
urllib3==1.25.3
wcwidth==0.1.7
webencodings==0.5.1
widgetsnbextension==3.5.1
wrapt==1.11.1
yarl==1.3.0`

And pip 19.2.3

**Comment by C4ptainCrunch** [comment]
I'm using the same pip and python version as you and i can't reproduce the problem.

1. How do you import the lib ? With `from ics import Calendar` ?
2. What OS are you running ?
3. Did you try removing your virtualenv and creating/installing it again ?

**Comment by matthewdenaburg1** [comment]
I'm having the same issue. 

I'm running Ubuntu 18.04.3 under WSL. 
Python version 3.6.8
Installed using `pip3 install ics`
pip version: `pip 19.3.1 from /usr/local/lib/python3/dist-packages (python3.6)`
Not using virtual environments

`pip3 freeze` output:
```
arrow==0.14.7
asn1crypto==0.24.0
astroid==1.6.0
attrs==17.4.0
Automat==0.6.0
beautifulsoup4==4.6.0
blinker==1.4
certifi==2019.9.11
chardet==3.0.4
click==6.7
cloud-init==19.2
colorama==0.3.7
command-not-found==0.3
configobj==5.0.6
constantly==15.1.0
cryptography==2.1.4
distro-info===0.18ubuntu0.18.04.1
Django==1.11.11
gmpy2==2.0.8
html5lib==0.999999999
httplib2==0.9.2
hyperlink==17.3.1
ics==0.6
idna==2.8
incremental==16.10.1
isort==4.3.4
Jinja2==2.10
jsonpatch==1.16
jsonpointer==1.10
jsonschema==2.6.0
keyring==10.6.0
keyrings.alt==3.0
language-selector==0.1
lazy-object-proxy==1.3.1
logilab-common==1.4.1
lxml==4.2.1
MarkupSafe==1.0
mccabe==0.6.1
netifaces==0.10.4
oauthlib==2.0.6
PAM==0.4.2
pyasn1==0.4.2
pyasn1-modules==0.2.1
pycrypto==2.6.1
pygobject==3.26.1
PyJWT==1.5.3
pylint==1.8.3
pyOpenSSL==17.5.0
pyserial==3.4
python-apt==1.6.4
python-dateutil==2.8.1
python-debian==0.1.32
pytz==2018.3
pyxdg==0.25
PyYAML==3.12
requests==2.22.0
requests-unixsocket==0.1.5
SecretStorage==2.3.1
service-identity==16.0.0
six==1.13.0
smartystreets-python-sdk==4.3.0
sqlparse==0.2.4
ssh-import-id==5.7
systemd-python==234
TatSu==4.4.0
Twisted==17.9.0
ufw==0.36
unattended-upgrades==0.1
urllib3==1.25.6
webencodings==0.5
wrapt==1.9.0
zope.interface==4.3.2
```


I'm having this issue in a python script, and when I do the following:
- `python3 -c 'import ics'`
- `python3 -c 'from ics import Calendar'`

The output is exactly the same for both:
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/USER/.local/lib/python3.6/site-packages/ics/__init__.py", line 3, in <module>
    from .alarm import AudioAlarm, DisplayAlarm
  File "/home/USER/.local/lib/python3.6/site-packages/ics/alarm/__init__.py", line 1, in <module>
    from ics.alarm.audio import AudioAlarm
  File "/home/USER/.local/lib/python3.6/site-packages/ics/alarm/audio.py", line 3, in <module>
    from ics.alarm.base import BaseAlarm
  File "/home/USER/.local/lib/python3.6/site-packages/ics/alarm/base.py", line 6, in <module>
    from ics.component import Component
  File "/home/USER/.local/lib/python3.6/site-packages/ics/component.py", line 6, in <module>
    from .utils import get_lines
  File "/home/USER/.local/lib/python3.6/site-packages/ics/utils.py", line 6, in <module>
    import arrow
  File "/home/USER/.local/lib/python3.6/site-packages/arrow/__init__.py", line 3, in <module>
    from .api import get, now, utcnow
  File "/home/USER/.local/lib/python3.6/site-packages/arrow/api.py", line 10, in <module>
    from arrow.factory import ArrowFactory
  File "/home/USER/.local/lib/python3.6/site-packages/arrow/factory.py", line 11, in <module>
    import calendar
  File "/home/USER/git/calendar/calendar.py", line 3, in <module>
    import requests
  File "/home/USER/.local/lib/python3.6/site-packages/requests/__init__.py", line 112, in <module>
    from . import utils
  File "/home/USER/.local/lib/python3.6/site-packages/requests/utils.py", line 26, in <module>
    from ._internal_utils import to_native_string
  File "/home/USER/.local/lib/python3.6/site-packages/requests/_internal_utils.py", line 11, in <module>
    from .compat import is_py2, builtin_str, str
  File "/home/USER/.local/lib/python3.6/site-packages/requests/compat.py", line 59, in <module>
    from http import cookiejar as cookielib
  File "/usr/lib/python3.6/http/cookiejar.py", line 41, in <module>
    from calendar import timegm
ImportError: cannot import name 'timegm'
```

Any suggestions?

**Comment by N-Coder** [comment]
@alex27riva the issue here is that you have a file named `ics.py`, which shadows the name of the library. Rename your file and the import error will be gone.
Similarly for @matthewdenaburg1, you also had a file named `calendar.py` shadowing the module used by `cookiejar.py` (which was included from requests and is thus completely unrelated from this project).
Actually, those bugs albeit being surprising at first are pretty easy to detect, if the name of the module that fails to import already appears further up your stacktrace, you usually have a [file name collision with a module](http://python-notes.curiousefficiency.org/en/latest/python_concepts/import_traps.html#the-name-shadowing-trap) (or some cyclic dependencies). 

@tomschr maybe we should include a little warning about this issue in the docs.
