### ISSUE TITLE
blackslash missing in a summay after parsing ics file

### ISSUE THREAD

**Issue by jinqiyannan** [C4ptainCrunch/ics.py#198]
when there is a "\\" in the summay of an event in a ics file, after parsing, the "\\" is missing.
For example i have downloaded SV_en.ics file from google calendar, there is a festival whose summary is "National Day of Life\\, Peace and Justice\n", after parsing the file, i got the festival with a name of "National Day of Life, Peace and Justice". The back slash is missing, how can i fix this problem

**Comment by C4ptainCrunch** [comment]
Hi!
Could you add here an example ics file that triggers your issue ?
If you can, please make it as small as possible while still triggering the issue.
(Also please make sure you are not uploading personal data)

Thank you :hugs:

**Comment by jinqiyannan** [comment]
Thank you for your reply, I am sorry i cannot support this ics file through my company's network,  since it has some harsh restrictions relating to sending data outside. But i think you can download this SV_en.ics file from google calendar website or you may add a backslash in the summary(name) field of a event in any ics file and try parsing this file with: cal = Calendar(open(pathTOIcs)), and you may see the backslash  in the name of that altered event missing.

**Comment by C4ptainCrunch** [comment]
Could you maybe link me this `SV_en.ics` ? Or just paste the relevant part directly inline over here ? :)
(or i can just wait until you are outside your corporate network)

**Comment by jinqiyannan** [comment]
please copy the text below and save it as test.ics file, then try to parse it. The only event in this ics file has the name as "National Day of Life\, Peace and Justice", which has a backslash in it. However after parsing it ,  cal = Calendar(open("test.ics")), event = list(cal.events)[0], name = event.name, backslash is misiing in the name field.
BEGIN:VCALENDAR
PRODID:-//Google Inc//Google Calendar 70.9054//EN
VERSION:2.0
CALSCALE:GREGORIAN
METHOD:PUBLISH
X-WR-TIMEZONE:UTC
BEGIN:VEVENT
DTSTART;VALUE=DATE:20190326
DTEND;VALUE=DATE:20190327
DTSTAMP:20180613T093957Z
UID:20190326_60o30pj36so30c1g60o30dr56c@google.com
CLASS:PUBLIC
CREATED:20150603T225138Z
DESCRIPTION:
LAST-MODIFIED:20150603T225138Z
SEQUENCE:0
STATUS:CONFIRMED
SUMMARY:National Day of Life\, Peace and Justice
TRANSP:TRANSPARENT
END:VEVENT

**Comment by N-Coder** [comment]
This is actually working as intended, as a comma within a value needs to be [escaped by prefixing it with a backslash](https://www.ietf.org/rfc/rfc2445.html#page-46) in the file. If you look at the event in any calendar application, its title will contain no backslash before the comma, as the escape is undone when parsing the file. If you want to have an actual backslash before a comma in the value (i.e. the text appearing as `\,` in an application), the serialized form would have to be `\\\,`.
