### ISSUE TITLE
Setting an events .extra field to a list throws an error in the events __str__ method

### ISSUE THREAD

**Issue by hanslub42** [C4ptainCrunch/ics.py#208]
When trying to follow [the manual](https://icspy.readthedocs.io/en/stable/advanced.html#custom-properties) I ran into problems

```python
import ics
e = ics.Event('blah')
extra_content = ics.utils.ContentLine(name="FOO", value="BAR")
e.extra = [extra_content] # the manual seems to suggest this 
print(e)
```

This throws an error when printing the event:                                                                                                     

```python   
File "/home/hlub/.local/lib64/python3.6/site-packages/ics/component.py", line 70, in __str__
container = self.extra.clone()
 AttributeError: 'list' object has no attribute 'clone'
```

Replacing the `e.extra = [extra_content]` by `e.extra.append(extra_content)` solves the problem. Actually, the manual doesn't directly say how to set the `.extra` field, only how it gets set when reading a `.ical` file.  Being able to properly set it is important  for people who want to _write_ iCalendar files as opposed to reading/parsing them.

**Comment by C4ptainCrunch** [comment]
Thanks @hanslub42 for the report ! The documentation is indeed wrong and `.extra` should be a `Container` and not a list (and it's better to `.extend` the `Container` instead of overriding it).

**Comment by N-Coder** [comment]
This is also fixed by the [Component.extra](https://github.com/C4ptainCrunch/ics.py/pull/222/files#diff-23909cb717da4909ac47419eae4a4603R24) validator: `instance_of(Container)` in #222

**Comment by C4ptainCrunch** [comment]
:tada:
