### ISSUE TITLE
After parsing an iCal file, event.attendees is empty

### ISSUE THREAD

**Issue by mafrosis** [C4ptainCrunch/ics.py#209]
The ical file came from a Calendar component in a Confluence page - I can probably clean up for public consumption if you need a test case.

Has this problem come up before? I thought it must be me doing something wrong.. at first.

**Comment by mafrosis** [comment]
I have found `ATTENDEES` lurking in the `.extra` attribute on `Event`. I can hack my way around this for now - but would prefer to contribute upstream. 

Are there some notes on how the parser works somewhere? I'll read the source in more detail when I get time. I see `Event.Meta.parser = EventParser`, and that class is missing a `parse_attendees`.

**Comment by C4ptainCrunch** [comment]
Good catch !
Indeed, we don't parse `ATTENDEES` on events (but we do on alarms, i don't know why).
Unfortunately we don't have documentation on how to write parsers at the moment
