### ISSUE TITLE
TypeError: Can't instantiate abstract class EmailAlarm with abstract methods action

### ISSUE THREAD

**Issue by doverradio** [C4ptainCrunch/ics.py#213]
Hello, I am constantly getting this error when trying to use your library for the first time:

TypeError: Can't instantiate abstract class EmailAlarm with abstract methods action

My code:
```
# ics_reader.py

from ics import Calendar, Event
import requests

r = requests.get(url_containing_ics_file)


c = Calendar(r.text)

c
```

I can confirm certainly r.text is getting the data because separately I am able to output it.  Why this error?

**Comment by RagingRoosevelt** [comment]
I'm on version `0.6` (installed via pip) and I'm getting the same error as @doverradio when I try to pull in my google calendar:

```python
from ics import Calendar
import requests
url = "https://calendar.google.com/calendar/ical/<my email>%40gmail.com/private-<secret key>/basic.ics"
c = Calendar(requests.get(url).text)
```

I was reading through the specific text of the error and bumped into this

> 'Multiple calendars in one file are not supported by this method. Use ics.Calendar.parse_multiple()')

I switched to 

```python
c = Calendar.parse_multiple(requests.get(url).text)
```
and I still get the error 

> TypeError: Can't instantiate abstract class EmailAlarm with abstract methods action

referencing line 28 in `ics/component.py`.  Ascending the stack trace, next is line 70 in `ics/alarm/base.py` and then line 77 in `ics/parsers/event_parser.py`.

**Comment by C4ptainCrunch** [comment]
Hey @doverradio and @RagingRoosevelt :wave: 

It looks like you found a bug :confused: Could you add here an example ics file that triggers your issue ?

If you can, please make it as small as possible while still triggering the issue.
(Also please make sure you are not uploading personal data)

Thank you :hugs:

**Comment by RagingRoosevelt** [comment]
Sorry for not getting an ical file for testing.  I was trying to figure out how to get a copy of my google calendar that doesn't include every single thing I've done of the last few years.

Anyhow, I tested the 0.7 release and it solved the error I observed.
