### ISSUE TITLE
Support for arrow 0.15

### ISSUE THREAD

**Issue by christofsteel** [C4ptainCrunch/ics.py#216]
Hi,
is there a reason ics does not support arrow 0.15? I needed ics and arrow >= 0.14 for a project, installed both and so far I had no incompatibilities (But I only did limited testing).

**Comment by N-Coder** [comment]
I'll be trying to remove Arrow entirely, because it is pretty bad at handling timezone-naive timestamps (also called "floating" by the RFC). See #222 for details.
