### ISSUE TITLE
`organizer` param on `Event.__init__()` doesn't do anything

### ISSUE THREAD

**Issue by gabelimon** [C4ptainCrunch/ics.py#217]
I was attempting to set `organizer` via the constructor but now I realize it has to be set after instantiation.

https://github.com/C4ptainCrunch/ics.py/blob/master/ics/event.py#L94

**Comment by C4ptainCrunch** [comment]
Indeed, that's a stupid bug, sorry about that :/
I'm divided between removing the parameter or fixing L94 though...

**Comment by gabelimon** [comment]
Why remove it? Seems like an easy fix

**Comment by N-Coder** [comment]
This is fixed by #214.
