### ISSUE TITLE
Parse error with NULL characters in TZID (not RFC compliant)

### ISSUE THREAD

**Issue by franc6** [C4ptainCrunch/ics.py#219]
A user of some of my software which uses ics reported a parse error.  Looking at the file, and trying a simple test, the problem is the ics file has embedded NULL characters in the TZID property (and property parameters) for a specific time zone.  I don't know what's producing the file yet; I'll update this issue after I find out.

I realize that NULL isn't allowed, per the RFC, but I can really only apply a sledge-hammer style work-around, which I suspect is far less efficient than a work-around in ics. :)

I've attached the file, as scrubbed by my user, for reference.

[calendar.2.zip](https://github.com/C4ptainCrunch/ics.py/files/4071583/calendar.2.zip)

**Comment by C4ptainCrunch** [comment]
What kind of fix would you propose at the ics.py level ?

**Comment by franc6** [comment]
I'm not sure it's even a good idea to do it in ics.py. :)  My original thought was that it's likely memory usage could be reduced by making such substitutions only for smaller strings.  Taking a cursory look at the code, something along the lines of remove_x and remove_sequence, that removes NULL and any other obviously wrong, but common character?
Again, I don't know if that's really a good idea or not -- it just seems like it would be more memory (and maybe time) efficient.
Thanks!

**Comment by N-Coder** [comment]
I think that broken strings isn't a thing we should be special-casing for deep within the library. Strings are used in pretty much all places and trying to put nulls in there will get messy.
There are pretty good and [specialized preprocessing tools](https://stackoverflow.com/questions/2398393/identifying-and-removing-null-characters-in-unix) that can help out.
If you don't want to use any of these, the best thing to do would probably loading the file in binary mode, replacing all the nulls manually and than calling decode manually before passing the now valid string to the library.
This is doable in a few lines of python and if (but only if!) it is required by multiple people, we could put the preprocessing code into the docs. Do you know why Microsoft Exchange Server 2010 put the nulls in there and whether that is reproducible and might affect other people?

Talking about efficiency here pretty much sounds like [premature optimization](http://wiki.c2.com/?PrematureOptimization). We don't even know whether adding that preprocessing step might ever become a bottleneck - and I highly doubt that it ever may. If you want to parse huge, broken ics files with only very little memory fast, you probably should neither use python nor this library, but craft a solution specifically optimized for that use-case. For all other cases, the above should suffice.

**Comment by franc6** [comment]
Thanks!  It's sounding like a worse idea all the time. :)
I've no idea why it's putting NULLs in there, but at a guess -- the time zones with NULL characters all make the TZID exactly 32 characters long; somebody used a fixed-width buffer assuming it would be treated as a NULL-terminated string, and somebody else just dumped the contents of the buffer based on the length of the buffer, instead of treating it as a NULL-terminated string. :)
Regarding optimization; I'm not in a good position to determine that, which is why I ask.  :) I think originally I was thinking the parsing might happen on a more character-oriented basis, such that invalid characters could be easily skipped, but it doesn't look like that's the case.  If it does become a problem, I'll probably switch out the python for something I am more familiar with, and generate python bindings from there (the environment calling my code assumes a python module).
Again, thanks for taking the time to look and reply!  I consider this issue adequately resolved.
