### ISSUE TITLE
Doesn't work with Python < 3.8 since latest TatSu release

### ISSUE THREAD

**Issue by andialbrecht** [C4ptainCrunch/ics.py#221]
A few hours ago TatSu release version 5.0 of their module which requires Python >= 3.8. Since ics has only "tatsu>4.2" in it's requirements on a fresh install the newest version of TatSu will be installed which breaks compatibility with Python < 3.8

I'm not sure how dependencies are handled in this project. But would it be a solution to pin tatsu to ">4.2,<5" in requirements.txt and make a new release?

**Comment by C4ptainCrunch** [comment]
Oh, this is sad that TatSu breaks compatibility with >90% of python installs, keeping at least 3.7 would have been better :)

> But would it be a solution to pin tatsu to ">4.2,<5" in requirements.txt and make a new release?
Yes, it's that simple :)

**Comment by N-Coder** [comment]
We could use an [environment marker](https://stackoverflow.com/a/33451105) to fix this. I'll open a small PR for this once I have time.

**Comment by N-Coder** [comment]
I created a PR that explicitly restricts tatsu to <5 for python 3.7 and below.
But it seems that pip is already automatically doing this, see e.g. the [CI run](https://github.com/C4ptainCrunch/ics.py/pull/227/checks?check_run_id=447936805#step:4:22) of this completely unrelated PR, which used tatsu 4.4 on python 3.7 without an explicit version limit and thus also worked flawlessly.
@andialbrecht do you know how this weird situation came up on your system and whether / how that can be reproduced? Obviously, its happening on none of the 4 CI instances, all of which use python <3.8.

**Comment by C4ptainCrunch** [comment]
Closing until we have more info

**Comment by andialbrecht** [comment]
ah, sorry, I've missed the mention by @N-Coder above. I've tried to reproduce it and you're right: when installing ics in an environment using Python <3.8 the correct version of tatsu (<5) is installed as a dependency. 
I'm only able to reproduce this error when I'm using an (pretty much outdated) version of DevPI as a PyPI proxy inbetween. So sorry for the noise! I didn't expect that this devpi proxy could be an issue here.
