### ISSUE TITLE
Timeline.today() requires useless day argument

### ISSUE THREAD

**Issue by sjoerdsein** [C4ptainCrunch/ics.py#224]
If one wants to generate all events that occur today (on the day the code gets executed) one would call [`Timeline.today()`](https://github.com/C4ptainCrunch/ics.py/blob/683b338eea12558336d272ad696741a8fb055dcc/ics/timeline.py#L98-L105). For any other day one would call [`Timeline.on(day)`](https://github.com/C4ptainCrunch/ics.py/blob/ed14cde096ad5b50bfa768c1fd32892eba744087/ics/timeline.py#L84-L96). This function is also called by `Timeline.today()`.
Still `Timelinle.today()` requires a `day` argument to be provided, which is then not used.
https://github.com/C4ptainCrunch/ics.py/blob/683b338eea12558336d272ad696741a8fb055dcc/ics/timeline.py#L98-L105
A Minimal Working Example:
```python3
#!/usr/bin/env python
from ics import Calendar, Event
from ics.timeline import Timeline
from datetime import timedelta
import arrow

e = Event(name="My Cool Event", begin=arrow.now(), duration=timedelta(hours=2))
t = Timeline(Calendar(events=[e]))

print("Today's events:    ", list( t.today(day=None) ))
# Returns today's events, as expected

yesterday = arrow.now().shift(days=-1)
print("Yesterday's events:", list( t.today(day=yesterday) ))
# Still returns today's events, while we might expect yesterday's

print("Today's events:    ", list( t.today() ))
# TypeError: today() missing 1 required positional argument: 'day'
```
I would suggest to either remove the `day` argument or to have it default to `arrow.now()` and forward it to `self.on()`. The first case would not be backward compatible but may expose bugs in users' code. In the second case `Timeline.today()` and `Timeline.on()` would be equivalent which is confusing and goes against Python's ["there should be only one obvious way to do it"](https://www.python.org/dev/peps/pep-0020/) principle, and the docstring should be updated as well. But it is backward compatible.

**Comment by C4ptainCrunch** [comment]
Thanks for this detailed bug report @sjoerdsein :+1: 

As we already have `.on()` and that `.today()` just calls `.on(arrow.now())` i'd say we can choose the solution were we remove the argument. After all, we are still in beta, we can may the API :)

You you be OK to open a PR with the change ?
