### ISSUE TITLE
Trigger in audio.py invalid syntax

### ISSUE THREAD

**Issue by sekrev** [C4ptainCrunch/ics.py#250]
Sorry, I don't know if this is a general issue or just my error. I just installed ics.py but with the example in the doc I get the following error:
from ics import Calendar, Event
c = Calendar()
e = Event()
e.name = "My cool event"
e.begin = '20140101 00:00:00'
c.events.add(e)
c.events
# {<Event 'My cool event' begin:2014-01-01 00:00:00 end:2014-01-01 00:00:01>}

executing leads to:
python test.py
Traceback (most recent call last):
  File "test.py", line 1, in <module>
    from ics import Calendar, Event
  File "/usr/local/lib/python2.7/dist-packages/ics/__init__.py", line 3, in <module>
    from .alarm import AudioAlarm, DisplayAlarm
  File "/usr/local/lib/python2.7/dist-packages/ics/alarm/__init__.py", line 1, in <module>
    from ics.alarm.audio import AudioAlarm
  File "/usr/local/lib/python2.7/dist-packages/ics/alarm/audio.py", line 25
    trigger: Union[timedelta, datetime] = None,
           ^
SyntaxError: invalid syntax

audio.py has the following:

    class Meta:
        name = "VALARM"
        parser = AudioAlarmParser
        serializer = AudioAlarmSerializer

    def __init__(
        self,
        trigger: Union[timedelta, datetime] = None,
        repeat: int = None,
        duration: timedelta = None,
    ):

        super().__init__(trigger, repeat, duration)
        self._sound: Optional[ContentLine] = None

    @property
    def action(self):
        return "AUDIO"

I can't see there any invalid syntax?

Thanks,
Simon

**Comment by N-Coder** [comment]
Which python (version) on which system are you using?

**Comment by sekrev** [comment]
Thanks for the "hint" with the version. I used python 2.7. (which is really old), then I switched to 3.7 and everything worked fine.

Simon

**Comment by N-Coder** [comment]
Jep, we only support Python versions 3.6 and up and this is definitely an issue with Python 2.6 (which is no longer getting security fixes for quite some time now) not being able to handle the newer type annotation syntax, so I'm closing this issue.
