### ISSUE TITLE
Recurring events not happening

### ISSUE THREAD

**Issue by ttmx** [C4ptainCrunch/ics.py#258]
Hey!
I'm making a script to open my classes automatically with ics.py, to do this, I'm importing my google calendar ics file to ics.py, and using `timeline.Timeline(cal).now()` to iterate through classes I am having at this second.
Although I do have classes right now, and it did work last week(the week I put the classes in my calendar) it does not this week.
Seemingly recurring events are not handled. Am I doing something wrong? 

```py
cal_text = open("./calendar.ics").read()
cal = Calendar(imports=cal_text)

for i in timeline.Timeline(cal).now():
    print(i)
```
![image](https://user-images.githubusercontent.com/12669467/94424582-5d711380-0182-11eb-93b6-774c094649be.png)
Although I am having a class now, and this is the same .ics file as my google calendar, I get nothing printed.

Thank you!
Edit: I am using version 0.7 and python 3.8.5

**Comment by N-Coder** [comment]
You are right, recurring events are currently not properly supported, see #14, #168. The feature is on the wishlist for v0.8 and most of the required parts are already there, so it's mostly question of when I have the time to continue working towards the new release.

**Comment by ttmx** [comment]
You are correct, sorry!
I would be extremely glad if those could be implemented, as no python lib does it properly in my eyes. Thank you for your work until now!

**Comment by Rylon** [comment]
> You are right, recurring events are currently not properly supported, see #14, #168. The feature is on the wishlist for v0.8 and most of the required parts are already there, so it's mostly question of when I have the time to continue working towards the new release.

Hi @N-Coder , I just found this issue myself, my own fault for not reading the "known limitations" section of the README, but there we are 😂. My own use case is just to be able to have recurring events including in the `.timeline.today()` function, in a read-only form.

Is it possible there are enough pieces of this written that I could cobble together what I need locally in the meantime, while waiting for v0.8? I've looked at a few other libraries and this is the most Pythonic, so I'd like to stick with it.

**Comment by N-Coder** [comment]
If you want a quick and dirty way with v0.7, you could try to grab all the RRULE related values from `Event.extra` and pass them together with `Event.start` (i.e. DTSTART) to [`dateutil.rrulestr`](https://dateutil.readthedocs.io/en/stable/rrule.html#dateutil.rrule.rrulestr) to get them parsed properly. Then you can do your own rrule-enabled [`Timeline`](https://github.com/C4ptainCrunch/ics.py/blob/version-0.7/ics/timeline.py#L20) version by simply throwing events back into the heap if they have a pending recurrence, maybe similar to this:
```python
heap = [(x, x.start, rrules[x]) for x in self._calendar.events if x.begin is not None]
heapq.heapify(heap)
while heap:
    event, start, recurrences = heapq.heappop(heap)
    yield event, start
    try:
        # requeue the next occurrence if there is one
        heappq.heappush(heap, (event, next(recurrences), recurrences))
    except StopIteration:
        pass
```

I'll add something similar to v0.8 at some time, but right now you're probably better off with v0.7 because the new parser is still strictly standard-observing and thus complains about most of the ics files that are out there in the wild.

**Comment by Rylon** [comment]
Hi, thanks for the suggestion @N-Coder what I ended up doing was a second pass of the data using the [recurring-ical-events](https://pypi.org/project/recurring-ical-events/) library, and then instantiating a load of ICS `Event` objects using that data, to add to the original timeline. Seems to be doing what I need so far, so I'm happy 👍

**Comment by thehammeredone** [comment]
As I'm playing around with 0.8 (nice work, btw, y'all) I figured I'd drop a note here.

Not sure if this'd be helpful, but I was handling recurring events that didn't appear in `timeline.today()` as such:

```
import regex
recur_re = regex.compile(r"BYDAY=(.*);")

...

    # Catch recurring events as opposed to the above, which doesn't handle recurrence.
    # Sort the list by begintime
    eventlist = list(c.events)
    eventlist.sort(key=lambda ev: ev.begin)
    for e in eventlist:
        # Pull the recurrence rule from the raw ICS
        rrule = recur_re.search(str(e))
        if rrule is not None:
            # Split into a list of day strings
            recur = rrule.group(1).split(",")
            for re_day in recur:
                # If today... do what we used to above with timeline.today()
                if re_day.lower() in day.lower():
                    do_work_here()
```
