### ISSUE TITLE
Recurring events ?

### ISSUE THREAD

**Issue by SnaKyEyeS** [C4ptainCrunch/ics.py#264]
Hello ! First of all, thanks for your work !

Secondly: I was wondering if there is any plan or else to support recurring events representation ? If no, how hard would it be to implement ?

**Comment by N-Coder** [comment]
Yes, maybe first check [this](https://github.com/C4ptainCrunch/ics.py/issues?q=is%3Aopen+recurring) out. Parsing support is already [implemented](https://github.com/C4ptainCrunch/ics.py/blob/timezones/src/ics/converter/special.py#L29) and waiting to be merged, while interpretation of the recurrences in the Timeline is still todo.
