### ISSUE TITLE
How to: Add an organizer to an event?

### ISSUE THREAD

**Issue by syedaminx** [C4ptainCrunch/ics.py#266]
Apologies in advance if this is a trivial question, but what's the proper format to add an organizer to the event? 

If I pass in a string, I can't pass in both, a `common_name` and an `email`. If I pass in an object, I get a serializer error. The documentation says an `Organizer` object is expected and from looking at the code it looks like the `Organizer` class takes in a `Person`. I wasn't able to get much further on how to do this. Can someone show me a small code example of how to include the common name and email for the organizer?

**Comment by aureooms** [comment]
Related #207

**Comment by syedaminx** [comment]
> Related #207

I did see this, it appears that the string type is no longer supported. However, I'm still getting a serializer error when passing in an object.

If you are familiar with it, would you mind letting me know what I'm doing wrong in the following code block?

`event.organizer = {"common_name": "Name", "email": "123@gmail.com"}`

Thank you.

**Comment by N-Coder** [comment]
Use the [`Organizer`](https://github.com/C4ptainCrunch/ics.py/blob/version-0.7/ics/attendee.py#L73) class, which inherits from [`Person`](https://github.com/C4ptainCrunch/ics.py/blob/version-0.7/ics/attendee.py#L16):
```
event.organizer = Organizer(common_name="Name", email="123@gmail.com")
```
