### ISSUE TITLE
Android import error (missing DTSTAMP)

### ISSUE THREAD

**Issue by tomfrankkirk** [C4ptainCrunch/ics.py#267]
I've been having trouble getting ics files created by ics.py to play nicely with calendars on Android phones. In particular there seem to be two issues: 

1. string encoding with BOM. Admittedly, this is not an ics.py problem, but I've found that writing to files without a leading BOM character is more reliable for use on android and thought it would be worth pointing out. 

2. exported events missing a DTSTAMP field, with no option to add one in via code (or rather, the docs don't mention this?). This issue seems to be inconsistent across android devices, namely, some have an issue with it, others don't seem to mind. I've managed to clear this up by just manually editing files to add the DTSTAMP file in, so I'm fairly certain this is the issue. 

This thread mentions both issues: https://stackoverflow.com/questions/35918537/android-google-calendar-unable-to-launch-event

I'd be happy to push a small patch on for DTSTAMP. In particular, I was thinking that upon `Event` creation, DTSTAMP is taken as `datetime.now()`, unless the user explicitly overwrites it subsequently? It would then just need casting to text in the same form as the other date time fields.

**Comment by N-Coder** [comment]
Hey, we do have support for the `DTSTAMP` field, although in the current version 0.7 there was some confusion around this field and the member of the Event object is actually called `created` (while the corresponding [field in the ics file](https://github.com/C4ptainCrunch/ics.py/blob/version-0.7/ics/serializers/event_serializer.py#L9) is `DTSTAMP` and a `CREATED` field in the ics file is moved to the `Event.extra` array). Currently, the field doesn't have a default, but you can definitely pass a value upon creation. In the upcoming version 0.8 these two fields will be properly separated and have [sensible defaults](https://github.com/C4ptainCrunch/ics.py/blob/master/src/ics/event.py#L35).

**Comment by tomfrankkirk** [comment]
That seems to have solved it, thanks very much for the pointer! Definitely saved me some effort there...
