### ISSUE TITLE
Clean stacktrace for users

### ISSUE THREAD

**Issue by C4ptainCrunch** [C4ptainCrunch/ics.py#41]
If an user gives something wrong to the lib, the stacktrace should stop at the first level of the lib and not go deeper.

**Comment by guyzmo** [comment]
well, I believe it's never bad to have too much verbosity within a lib when something breaks. But if you really want to go that way, you should consider catching exception at the "first level", but reraise so it's easy to see which part of the stacktrace is internal, which part is external to the lib! Something like:

    except Exception, err:
        raise IcsException("Fatal: {}".format(err)) from err

Just do not shadow internals, or you'll make debugging of the lib harder for your lib users! ☺

**Comment by C4ptainCrunch** [comment]
Yup, it seems like a stupid idea of mine...
