### ISSUE TITLE
Enhance doc to show that SUMMARY == Event.name

### ISSUE THREAD

**Issue by sils1297** [C4ptainCrunch/ics.py#66]
I have a SUMMARY field in my ics which I can't seem to access via ICS. Any workaround available?

**Comment by sils1297** [comment]
it's the name property but kind of hard to find ;) maybe documentation improvement needed?

**Comment by C4ptainCrunch** [comment]
What would you suggest ?

**Comment by sils1297** [comment]
@C4ptainCrunch a `summary` property would be cool or documentation for `name` here: http://icspy.readthedocs.org/en/latest/api.html#event
