### ISSUE TITLE
How to set Timezone for Event?

### ISSUE THREAD

**Issue by fastcrash** [C4ptainCrunch/ics.py#67]
Hi,

thanks for this great work so far. There is only one thing I haven't figured out yet. How do I set the Timezone for DTSTART and DTEND?

**Comment by C4ptainCrunch** [comment]
Hi !

Every timestamp in ics.py is an [Arrow](http://crsmithdev.com/arrow/) object so you can simply pass an Arrow object that has a timezone as `begin` or  `end`.
Does that answers your question ? :)

**Comment by bhavik2491** [comment]
@C4ptainCrunch 
Hi !

Do we provide VTIMEZONE support while creating ics file ?If yes whcih API needs to get called ?
I'm asking about during creating ics file not during parsing time.
