### ISSUE TITLE
event equality

### ISSUE THREAD

**Issue by ConnyOnny** [C4ptainCrunch/ics.py#71]
Event equality currently only checks for uid equality. This leads to strange situations:

``` python
e2 = e1.clone()
e2.begin=#something different than in e1
if e1 == e2:
    print("this will be printed")
```

I think event equality should check if all the members are the same.

**Comment by C4ptainCrunch** [comment]
You are right, i'll change that.
(Bonus : when cloning an event, we should also change the uid)

**Comment by C4ptainCrunch** [comment]
Should i test the uid in event equality ? It seems more like the "is" keyword should do that.

**Comment by ConnyOnny** [comment]
On cloning: I think changing something (e.g. the uid) on cloning would be *very* surprising for users of this library. I strongly recommend you don't do that.
I think if begin, end, name, description, location... all match, two events should be considered as equal, whatever their uids are. Especially: If an event has no uid I think ics.py generates it. So if you load the same calendar file twice, the events could be considered not equal.
On the other hand:
```python
e2 = e1.clone()
e2.uid = # something else
if e1 == e2:
    print("will be executed")
```

How about this: We generate the uid as a hash value from all the other fields of an event. So if an event is loaded twice, it will always get the same uid, which means we can use the uid in the `eq`-method without it beaing awkward.
