### ISSUE TITLE
ICS does not support timezone aware datetime objects

### ISSUE THREAD

**Issue by mnolet** [C4ptainCrunch/ics.py#79]
I banged my head against a wall for a while on this one as I was getting very strange timezones back.

There appears ot be a bug in Arrow where if you pass it a timezone aware object it misbehaves.

I submitted a bug there with more details, but logging this issue here in case anyone else runs into something similar: https://github.com/crsmithdev/arrow/issues/304

My solution was to strip the timezone from the datetime and then apply it to a non-timezone aware arrow object before assigning to begin.

**Comment by pganssle** [comment]
In case anyone following this didn't check the resolution on the arrow issue, this was not a bug in arrow or in ICS, it was an issue with how @mnolet was constructing their datetimes. Using `dateutil` time zones or using `pytz` timezone with `localize` to properly construct your `datetime` objects will solve the issue.

**Comment by aureooms** [comment]
Thanks @pganssle !
