### ISSUE TITLE
support for ToDo items

### ISSUE THREAD

**Issue by slavkoja** [C4ptainCrunch/ics.py#82]
please, add support for VTODO icalendar items

**Comment by C4ptainCrunch** [comment]
Hello,

Right now i don't have enough time to implement it but if you submit a pull request, i'll review it happily :)

**Comment by eega** [comment]
Hi,

I have implemented VTODO support and sent you a pull request :)

**Comment by phintec** [comment]
Is this pull request scheduled to be reviewed sometime soon?  Very interested, thanks.

**Comment by C4ptainCrunch** [comment]
Hi ! THe PR has been merged into 36f1553 :) It's on master right now but not released yet
