### ISSUE TITLE
Support ATTENDEE

### ISSUE THREAD

**Issue by dgouldin** [C4ptainCrunch/ics.py#98]
Unless I'm missing it, I don't see anywhere `ATTENDEE` lines are represented in `Event` objects. For my use case (parsing attendee response emails containing a `text/calendar` mime part), it would be highly useful to have attendee information included.

**Comment by danieltellez** [comment]
I've made a pull request with my first approach to implement ATTENDEEs support with ics.py. Hope would be useful.

https://github.com/C4ptainCrunch/ics.py/pull/112

**Comment by denny64** [comment]
@danieltellez Whats the status on merging this?

**Comment by danieltellez** [comment]
You can follow the status here: https://github.com/C4ptainCrunch/ics.py/pull/112

**Comment by C4ptainCrunch** [comment]
#112 was merged and released a while ago :)
