### ISSUE TITLE
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position ...

### ISSUE THREAD

**Issue by madEng84** [C4ptainCrunch/ics.py#99]
Hi all, i have a UnicodeDecodeError using ICS version 0.3.1 from PIP
```
from ics import Calendar, Event
import datetime
from django.utils.translation import ugettext

def create_ics_file()
   c = Calendar()
   e = Event()
   e.name = ugettext(u"Meeting at '{event_name}'").format(event_name="DÜSSELDORF").encode("utf-8")
   e.begin = datetime.datetime(2017, 10, 10, 10, 00, tzinfo=None)
   e.end = datetime.datetime(2017, 10, 10, 11, 00, tzinfo=None)
   c.events.append(e)

   with codecs.open("..../my_custom_ics.ics", "w", "utf-8") as f:
      f.writelines(c)
```

Here is the stack trace

> 
> Traceback (most recent call last):
>   File "<console>", line 1, in <module>
>   File "/home/server/projects/ics_project/project/apps/ics/utils.py", line 56, in create_ics_file
>     f.writelines(c)
>   File "/usr/lib/python2.7/codecs.py", line 710, in writelines
>     return self.writer.writelines(list)
>   File "/usr/lib/python2.7/codecs.py", line 377, in writelines
>     self.write(''.join(list))
>   File "/home/server/.virtualenvs/ics_project/lib/python2.7/site-packages/ics/icalendar.py", line 96, in __iter__
>     for line in str(self).split('\n'):
>   File "/home/server/.virtualenvs/ics_project/lib/python2.7/site-packages/ics/component.py", line 93, in __str__
>     output(self, container)
>   File "/home/server/.virtualenvs/ics_project/lib/python2.7/site-packages/ics/icalendar.py", line 266, in o_events
>     container.append(str(event))
>   File "/home/server/.virtualenvs/ics_project/lib/python2.7/site-packages/ics/component.py", line 93, in __str__
>     output(self, container)
>   File "/home/server/.virtualenvs/ics_project/lib/python2.7/site-packages/ics/event.py", line 386, in o_summary
>     container.append(ContentLine('SUMMARY', value=escape_string(event.name)))
>   File "/home/server/.virtualenvs/ics_project/lib/python2.7/site-packages/ics/utils.py", line 170, in escape_string
>     string = string.replace("\\", "\\\\")
> UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 59: ordinal not in range(128)
> 

I think the problem is here (icalendar.py row 266):
```
@Calendar._outputs
def o_events(calendar, container):
    for event in calendar.events:
        container.append(str(event))
```

Can you help me?

**Comment by madEng84** [comment]
Any news on this bug?
Tnx

**Comment by timfaner** [comment]
@madEng84  Here is problem:
```e.name = ugettext(u"Meeting at ## '{event_name}'").format(event_name="DÜSSELDORF").encode("utf-8")```  


`encode("utf-8")` is not necessary, this module has done this in  line 99, icalendar.py
